part of 'http.dart';
abstract interface class Endpoints {
  static const String baseUrl = 'https://al-adeep.com';
  static const String auth = '/auth';
  static const String user = '/user';
  static const String product = '/product';
  static const String order = '/order';
  static const String cart = '/cart';
  static const String payment = '/payment';
  static const String notification = '/notification';
  static const String setting = '/setting';
  static const String help = '/help';
  static const String about = '/about';
  static const String contact = '/contact';
  static const String forgetPassword = "/forget-password";
  static const String login = "/api/mobile/login";
  static const String logout = "/logout";
  static const String register = "/api/mobile/register";
  static const String profileUpdate = "/api/mobile/profile/update";
  static const String home = "/api/mobile/home";
  static const String courseDetails = "/api/mobile/course/";
  static const String subscribe = "/api/mobile/subscribe";
  static const String subscribeBundle = '/api/mobile/subscribe-bundle';
  static const String myCourses = '/api/mobile/my-courses/';
  static const String forum = "/api/mobile/forum/";
  static const String addPost = "/api/mobile/forum/post";
  static const String addReply = "/api/mobile/forum/reply";
  static const String quiz = "/api/mobile/quiz/";
  static const String quizSubmit = "/api/mobile/quiz/submit";
  static const String myResults = "/api/mobile/my-results/";
  static const String liveSessions = "/api/mobile/live-sessions/";
}